Create etcd image with etcd-backup script
Wattpad/etcd-backup pull request #2
Opened 2016-12-05 22:04 UTC by pbitty

2016-12-06 13:08 UTC, jharlap requested changes
- not entirely clear why this needs to package both etcd and the backup script in the same image. it seems like any etcd image would work with this backup tool so long as you volume mount the data dir.
- the backup script never cleans up after itself, so eventually disk space within the container will fill up.
- there is logging & metrics for the happy code path, but not so much for the unhappy code paths - you're going to appreciate some logging/metrics there when it's time to debug the running app.
- if you're using sudo, i think you need to specify such in the travis.yml.
- you might want to include a suggestion in the readme about using s3 lifecycle policies to purge old backups
- how do you ensure your tests run in the right order? specifically, how do you ensure all the etcd containers are up and ready before you get to `run_tests()`?

2016-12-06 13:08 UTC, jharlap commented on etcd-backup/etcd-backup.py
> +    while True:
just a tip: it would be a lot easier to read the program flow if, instead of using an infinite loop with several ways to break out of it (i.e., a mix of breaks and exceptions), you stated explicitly what the loop conditions are and just modified their state within the loop. currently it took me a few passes to get that this runs until should_shut_down=True OR upload & metrics succeed OR we reach a retry limit. i also had to scroll far away to find out what the retry limit _is_ even thought it's only used here.

2016-12-06 13:08 UTC, jharlap commented on etcd-backup/etcd-backup.py
> +    while True:
now i see that this is considered common practice in python. kinda icky to this non-pythonista, but maybe the right thing to do if it's idiomatic for python.

2016-12-06 13:08 UTC, jharlap commented on etcd-backup/etcd-backup.py
> +                raise e
you might want to generate logs and/or metrics here - you've given up on a backup and there's zero visibility into that event.

2016-12-06 13:08 UTC, jharlap commented on .travis.yml
> +  - sudo make test
why do you need sudo to run `make test`?

2016-12-06 13:08 UTC, jharlap commented on .travis.yml
> +  - sudo apt-get install build-essential
what do you need that for? awscli?

2016-12-06 13:08 UTC, jharlap commented on .travis.yml
> +  - sudo apt-get install build-essential
if you had said this was a python project, would it not already have a build toolchain and pip ready to use?

2016-12-06 13:08 UTC, jharlap commented on .travis.yml
> +  - sudo curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
they don't have docker-compose pre-installed?

2016-12-06 13:11 UTC, pbitty commented on .travis.yml
> +  - sudo make test
I did this as a quick hack, with the intention of looking it up later.  For some reason the test script fails when trying to create the `tmp` folder.

2016-12-06 13:12 UTC, pbitty commented on etcd-backup/etcd-backup.py
> +                raise e
In a case like this you get a stack trace as the error bubbles all the way out of the program.  I thought this would be clear enough.  I could wrap it in another error before raising.  Do you have any other suggestions?

2016-12-06 13:12 UTC, pbitty commented on etcd-backup/etcd-backup.py
> +    while True:
I'll rethink this if I can.

2016-12-06 13:31 UTC, jharlap commented on etcd-backup/etcd-backup.py
> +                raise e
ooohhh! didn't realize this would crash the program - just thought it'd give up on that backup and try again for the next one.

2016-12-06 13:32 UTC, jharlap commented on .travis.yml
> +  - sudo make test
may i introduce you to `mktemp(1)`? ;P

2016-12-06 13:33 UTC, andrewsykim commented on etcd-backup/etcd-backup.py
> +                raise e
LOL, what is this? golang?

2016-12-06 13:50 UTC, andrewsykim requested changes
Not done reviewing, laptop just running out of batteries! Will review again when I'm in.

2016-12-06 13:50 UTC, andrewsykim commented on Dockerfile
> +    wget "https://github.com/coreos/etcd/releases/download/v2.3.7/${ETCD_BUILD}.tar.gz" -O - | \
should v2.3.7 also be using ${ETCD_VERSION}?

2016-12-06 13:50 UTC, andrewsykim commented on README.md
> +      -e ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 \
Wouldn't you need hostNetwork to listen at 0.0.0.0? Otherwise the other members can't reach you.

2016-12-06 13:50 UTC, andrewsykim commented on etcd-backup/etcd-backup.py
> +LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
Not sure if this is idiomatic python, if not should include in the docs?

2016-12-06 13:50 UTC, andrewsykim commented on etcd-backup/etcd-backup.py
> +    return backup_dir
Why do we need to return this?

2016-12-06 13:50 UTC, andrewsykim commented on etcd-backup/etcd-backup.py
> +    return file_path
why do we need to return file_path here?

2016-12-06 13:50 UTC, andrewsykim commented on etcd-backup/etcd-backup.py
> +    api_key = os.getenv('DATADOG_API_KEY')
We should mention something about it in the README?

2016-12-06 13:50 UTC, andrewsykim commented on etcd-backup/etcd-backup.py
> +    api_key = os.getenv('DATADOG_API_KEY')
that you can optionally use datadog to send metrics that is

2016-12-06 14:27 UTC, pbitty commented
@jharlap  Regarding logging the unhappy code paths, I think we're ok with letting exceptions bubble up.

For metrics in the unhappy code paths, I was thinking of trying a different approach.  Instead of caring about when errors happen, we care about the absence of a success.

So we'd alert on the _lack_ of backup metrics, instead of looking for failed backups.  I actually think we should do the same for our current DB and Redis backups, because we are actually open to the situation where the failure metric reporting doesn't work (it has happened before), and we were unaware that a backup wasn't happening.

What do you think?

2016-12-06 15:06 UTC, pbitty commented on etcd-backup/etcd-backup.py
> +            break
@jharlap, this is why I had to use the infinite loop.

2016-12-06 16:16 UTC, pbitty commented
Changes addressed.  R please?

2016-12-06 18:39 UTC, pbitty commented
@jharlap  I tried using `mktemp` to avoid having to run the tests under `sudo`, but it still had issues cleaning up because the files are created inside a container, by procs running as root.

It works on my machine I believe because I'm running Docker for Mac, which handles the permissions translation and keeps host-level permissions separate from container-level permissions.  Anyway, I'm going to leave as is for now, and re-visit if it becomes an issue.

2016-12-06 20:19 UTC, pbitty commented
So... I forgot an important point, we only want this running on one host at a time.   So we need some way to lock.  [This person](https://crewjam.com/etcd-aws/) just checked if we were running on the leader and only did the backup on the leader.   We really could just be using his code, but I wasn't confident in his process of just scanning the tree.

Anyway, I'll push more commits soon.

2016-12-06 22:05 UTC, andrewsykim commented on README.md
>  # docker-etcd
update this?

2016-12-06 22:06 UTC, andrewsykim commented on README.md
> +## Leader Backups
You probably considered this already, what happens when leader election changes during backup?

2016-12-06 22:07 UTC, pbitty commented on README.md
> +## Leader Backups
We'll eventually have a snapshot from the latest leader.  I'm not too concerned.  Backups will always be a bit stale.  I'm more concerned with them being consistent.

2016-12-06 22:09 UTC, pbitty commented on README.md
> +## Leader Backups
I'm not sure if the following is possible, as I don't know exactly how etcd implements Raft, but:

It may be possible in a network partition that a peer thinks it is the leader when it is not.  In that case we may have uploads from two "leaders".  We'd just have to figure out which one is the real one.  I don't think it's worth digging into it too much at this point.

2016-12-06 22:13 UTC, pbitty commented
@andrewsykim @jharlap Ready for review again.

2016-12-07 03:10 UTC, andrewsykim approved these changes

2016-12-07 14:04 UTC, jharlap commented on README.md
> +## Leader Backups
I agree that you don't need to sweat it. Stop reading here if you don't want the details ;)

I don't think it is a question of how _etcd_ implements Raft - it's just a property of Raft that for a short time after a network fault (i.e., until the heartbeat interval ends) a former leader who is now in a minority partition will still believe it is the leader. However, writes are only _committed_ after a quorum of nodes have stored the write, so even though the leader is still a leader, it will never manage to get a quorum of writes so it will not commit the change and thus the cluster is unavailable during this time period. Once the heartbeat interval fires, a new leader is elected within the majority partition (assuming the majority is enough to achieve quorum) and then the cluster becomes available again (assumption: clients can reach the new leader).

2016-12-07 14:08 UTC, andrewsykim commented on README.md
> +## Leader Backups
I always want the details :P

2016-12-07 14:46 UTC, pbitty commented on README.md
> +## Leader Backups
Me too.  :)  @jharlap That makes sense to me.

I'm more curious about the leader left behind in the minority partition.  It won't be able to commit writes as you said, but elections will also fail in the minority partition.  In that case, what does the node report as its `state`?

Not sweating it for now.  Bigger 🌽 to plant and harvest.

2016-12-07 15:24 UTC, jharlap requested changes
your test suite will print out success vs failure, but the exit code of the test is always 0 so travis will think it passes even when it fails

2016-12-07 17:27 UTC, pbitty commented
Silly me.  Test fixed.  R?

2016-12-08 01:52 UTC, merged